<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMHkTvYX\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMHkTvYX/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMHkTvYX.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMHkTvYX\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMHkTvYX\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MHkTvYX',
    'container.build_id' => '8107aa7b',
    'container.build_time' => 1529254638,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMHkTvYX');
