<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGyJErWY\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGyJErWY/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGyJErWY.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGyJErWY\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGyJErWY\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'GyJErWY',
    'container.build_id' => '3a032017',
    'container.build_time' => 1527792713,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGyJErWY');
